# Docker环境配置
spring:
  redis:
    host: redis
    port: 6379
    password: 
    database: 0
    timeout: 2000ms
  
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    connection-timeout: 15000

# 日志配置
logging:
  level:
    com.example.queue: INFO
    org.springframework.amqp: WARN
    org.springframework.data.redis: WARN
